// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jphfrvtnpgxswgalqgwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwaGZydnRucGd4c3dnYWxxZ3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NTg5NjIsImV4cCI6MjA3NjMzNDk2Mn0.mV7DmOmvObKCl8ehQeEoMejzqxj1GQFKGFLWBU2aF4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});